#!/bin/sh

#echo "Calling common script to set up environment"
#source ../../common/common.env
#source /opt/app/datartr/dmaap1/setJavaHome.sh
#echo "Common environment set up"

#echo "swm testing"
#cd /opt/app/datartr/dmaap1/tomcat_2/apache-tomcat-7.0.64/bin
#exec sh -x ./shutdown.sh
#echo "tomcat stopped"



#echo "Running common install pre proc"
#cd ../../common
#exec sh -x ./install_preproc.sh
